import { hashSync } from "bcrypt-ts";

const sampleData = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: hashSync("123456", 10),
      role: "admin",
    },
    {
      name: "Leslie",
      email: "user@example.com",
      password: hashSync("123456", 10),
      role: "user",
    },
  ],
  products: [
    {
      name: "Hyundai Accent 2020",
      slug: "hyundai-accent-2020",
      category: "AC Compressor",
      description: "Classic Polo style with...",
      images: [
        "/products/accent-gas20-1.png",
        "/products/accent-gas20-2.png",
        "/products/accent-gas20-3.webp",
      ],
      price: 6000,
      brand: "Hyundai",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Toyota Altis 2008",
      slug: "toyota-altis-2008",
      category: "AC Compressor",
      description: "Classic Polo style with...",
      images: [
        "/products/altis08-1.png",
        "/products/altis08-2.png",
        "/products/altis08-3.webp",
      ],
      price: 6200,
      brand: "Toyota",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Hyundai Eon",
      slug: "hyundai-eon",
      category: "AC Compressor",
      description: "Classic Polo style with...",
      images: [
        "/products/eon-1.png",
        "/products/eon-2.png",
        "/products/eon-3.webp",
      ],
      price: 6200,
      brand: "Hyundai",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Hyundai Getz",
      slug: "hyundai-getz",
      category: "AC Compressor",
      description: "Classic Polo style with...",
      images: ["/products/getz1.png", "/products/getz2.png"],
      price: 6200,
      brand: "Hyundai",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Hyundai Grand Starex",
      slug: "hyundai-grand-starex",
      category: "AC Compressor",
      description: "Classic Polo style with...",
      images: [
        "/products/grand-starex-1.png",
        "/products/grand-starex-2.png",
        "/products/grand-starex-3.webp",
      ],
      price: 6200,
      brand: "Hyundai",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Toyota Hi Ace 1997",
      slug: "toyota-hi-ace-1997",
      category: "AC Compressor",
      description: "Classic Polo style with...",
      images: [
        "/products/hi-ace97-1.png",
        "/products/hi-ace97-2.png",
        "/products/hi-ace97-3.webp",
      ],
      price: 6200,
      brand: "Toyota",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Hyundai Tucson",
      slug: "hyundai-tucson",
      category: "AC Compressor",
      description: "Classic Polo style with...",
      images: ["/products/tucson1.png", "/products/tucson2.png"],
      price: 6200,
      brand: "Hyundai",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Toyota Vios Batman",
      slug: "toyota-vios-batman",
      category: "AC Compressor",
      description: "Classic Polo style with...",
      images: [
        "/products/vios-batman-1.png",
        "/products/vios-batman-2.png",
        "/products/vios-batman-3.webp",
      ],
      price: 6200,
      brand: "Toyota",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Toyota Vios 2010",
      slug: "toyota-vios-2010",
      category: "AC Compressor",
      description: "Classic Polo style with...",
      images: [
        "/products/vios10-1.png",
        "/products/vios10-2.png",
        "/products/vios10-3.webp",
      ],
      price: 6200,
      brand: "Toyota",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Toyota Wigo",
      slug: "toyota-wigo",
      category: "AC Compressor",
      description: "Classic Polo style with...",
      images: [
        "/products/wigo-1.png",
        "/products/wigo-2.png",
        "/products/wigo-3.webp",
      ],
      price: 6200,
      brand: "Toyota",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
